fragment Best_sellersParts on Best_sellers {
  __typename
  name
  src
  category
  price
  piece
  link
}

fragment AnnouncementParts on Announcement {
  __typename
  message
  discount
  button
  link
  display
}
